# Generated by Django 2.0.4 on 2021-03-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ai_analysis_log',
            name='class_value',
            field=models.IntegerField(blank=True, db_column='class', null=True),
        ),
        migrations.AlterField(
            model_name='ai_analysis_log',
            name='confidence',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='ai_analysis_log',
            name='request_timestamp',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ai_analysis_log',
            name='response_timestamp',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
